<a href="https://colab.research.google.com/github/anushkalahare/Numpyfundamentals/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Array Basics

In [ ]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)

[1 2 3]
(3,)
int64
1
3
8


In [ ]:
print(a[0])
a[0] = 10
print(a)

1
[10  2  3]


In [ ]:
b = a * np.array([2,0,2])
print(b)

[20  0  6]


# Numpy Array vs Python List

In [ ]:
l = [1,2,3]
a = np.array([1,2,3])
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [ ]:
l.append(4)
l = l + [4]
l = l * 2
print(l)

a = a + np.array([4])
a = a * 2
print(a)

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]
[10 12 14]


In [ ]:
a = np.sqrt(a)
a = np.log(a)
print(a)

[1.15129255 1.24245332 1.31952866]


# Dot Product

In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

# numpy method 1
dot = np.dot(a1,a2)
print(dot)

# manual method 2
dot = 0
for i in range(len(l1)):
  dot += l1[i] * l2[i]
print(dot)

# manual method 3
sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)

# method 4
dot = a1 @ a2
print(dot)

32
32
32
32


# Speed test array vs list

In [1]:
import numpy as np

In [3]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
  dot = 0
  for i in range(len(A)):
    dot += A[i] * B[i]
  return dot

def dot2():
  return np.dot(a,b)

start = timer()
for t in range (T):
  dot1()
end = timer()
t1 = end-start

start = timer()
for t in range (T):
  dot2()
end = timer()
t2 = end-start

print('list calculations', t1)
print('numpy calculations', t2)
print(t1/t2)


list calculations 0.2278966600001695
numpy calculations 0.001602127999831282
142.246225035808


# Multidimensionsl Arrays

In [15]:
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)
print(a[0,0])
print(a[:,0])
print(a.T)
print(np.linalg.inv(a))
print(np.linalg.det(a))
print(np.diag(a))

c = np.diag(a)
print(np.diag(c))

[[1 2]
 [3 4]]
(2, 2)
1
[1 3]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[1 4]
[[1 0]
 [0 4]]


# Array Indexing/Slicing/Boolean Indexing

In [16]:
b = a[0,1]
print(b)

2


In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)

b = a[-1,-2]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [26]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

bool_idx = a > 2
print(bool_idx)
print(a[bool_idx])

print(a[a > 2])

b = np.where(a>2, a, -1)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [27]:
#fancy indexing

a = np.array([10,19,30,41,50,61])
print(a)
b = [1,3,5]
print(a[b])

[10 19 30 41 50 61]
[19 41 61]


In [30]:
a = np.array([10,19,30,41,50,61])
print(a)
even = np.argwhere(a%2==0).flatten()
print(a[even])

[10 19 30 41 50 61]
[10 30 50]


# Reshaping

In [32]:
a = np.arange(1,7)
print(a)
print(a.shape)
b = a.reshape(2,3)
print(b)
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [34]:
b = a[np.newaxis, :]
print(b)
print(b.shape)

[[1 2 3 4 5 6]]
(1, 6)


# Concatenation

In [38]:
a = np.array([[1,2],[ 3,4]])
b = np.array([[5,6]])
c = np.concatenate((a,b),axis=0)
print(c)
c = np.concatenate((a,b),axis=None)
print(c)
c = np.concatenate((a,b.T),axis=1)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 5]
 [3 4 6]]


In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#hstack, vstack
c = np.hstack((a,b))
print(c)
d = np.vstack((a,b))
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# Broadcasting

In [45]:
x = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
a = np.array([1, 0, 1])
y = x + a
print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]


# Functions and Axes

In [50]:
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))
print(a.std())
print(a.std(axis=0))
print(a.std(axis=1))
print(a.min())
print(a.max())
print(a.var())
print(a.var(axis=0))

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
[24 26 28 30 32 34 36]
[ 70 140]
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]
5.385164807134504
[5. 5. 5. 5. 5. 5. 5.]
[2. 2.]
7
23
29.0
[25. 25. 25. 25. 25. 25. 25.]


# Datatypes

In [55]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1.0,2.0], dtype=np.int32)
print(x.dtype)

x = np.array([1,2], dtype=np.float16)
print(x.dtype)

int64
float64
int32
float16


# Copying

In [56]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 10
print(a)
print(b)

[1 2 3]
[10  2  3]


# Generating Arrays

In [63]:
a =  np.zeros((2,3))
print(a)

a =  np.ones((2,3))
print(a)

a = np.full((2,3), 5.0)
print(a)

a = np.eye(3)
print(a)

a = np.arange(20)
print(a)

a = np.linspace(0,10,5)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.   2.5  5.   7.5 10. ]


# Random Numbers

In [73]:
a = np.random.random((3,2))
print(a)

a = np.random.randn(3,2) # normal/Gaussian distribution
print(a)
print(a.mean(), a.var())

a = np.random.randint(0,10,(3,2))
print(a)

a = np.random.choice(10, size=10)
print(a)

a = np.random.choice([-1,-6,-9], size=10)
print(a)

[[0.52073404 0.37844345]
 [0.05930896 0.99481845]
 [0.7190972  0.56180409]]
[[ 0.74781166 -1.16698515]
 [-0.49553253 -0.3253825 ]
 [-0.78441354 -0.28807666]]
-0.38542978759839525 0.34657648899522536
[[2 0]
 [8 0]
 [1 0]]
[3 9 9 6 4 0 5 9 6 4]
[-9 -1 -6 -6 -9 -9 -9 -1 -9 -6]


# Linear Algebra

1) Eigen values

In [79]:
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

# e_vec * e_val = A * e_vec

b = eigenvectors[:,0] * eigenvalues[0]
print(b)
c = a @ eigenvectors[:,0]
print(c)

print(np.allclose(b,c)) #to compare arrays

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
True


2) Solving linear systems

In [90]:
a = np.array([[1,1], [1.5,4]])
b = np.array([2200,5050])
x = np.linalg.inv(a) @ b
print(x)

x = np.linalg.solve(a,b)
print(x)

[1500.  700.]
[1500.  700.]


# Loading data from CSV file

In [ ]:
data = np.genfromtxt('data.csv', delimiter=',', skip_header=1)
print(data)
data = np.loadtxt('data.csv', delimiter=',', skiprows=1)
print(data)